# Dockerfile.dev
FROM node:14-slim

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose app port
EXPOSE 3000

# Default command for dev mode (with nodemon)
CMD ["npm", "run", "dev"]
